services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/site
    ports: 
      - 1313:1313
    command: hugo server --bind 0.0.0.0 --disableFastRender
    # stdin_open: true
