baseURL = "https://komenga.testhu.github.io"
title = "First Commit to..."
author = "Simone Weiß"
copyright = "Simone Weiß"
pagination.pagerSize = 10
languageCode = "en"
theme = "tailwind"
enableRobotsTXT = true
enableEmoji = true

[markup]
  _merge = "deep"

[params]
  keywords = "some, keywords, here"
  subtitle = "Tales from my first contributions to all kind of Open Source Software"
  contentTypeName = "posts"
  showAuthor = true

  [params.author]
  name = "Simone Weiß"
  email = "simone.p.weiss@posteo.com"

  [params.header]
    logo = "logo.svg"
    title = " A first contribution to..."

  [params.footer]
    since = 2025
    poweredby = true
  
  [[params.social_media.items]]
      enabled = true
      title = 'LinkedIn'
      icon = 'brand-linkedin'
      link = 'https://www.linkedin.com/in/simone-wei%C3%9F-954b641a4/'
  
    [[params.social_media.items]]
      enabled = true
      title = 'Github'
      icon = 'brand-github'
      link = 'https://github.com/simone-weiss'

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
